# Zephyr Dusk — sway client colors + wallpaper
output * bg ~/.img/wallpapers/zephyr_dusk_desktop.png fill

# class                  border   backgr.  text     indicator child_border
client.focused           #3DAEE9 #3DAEE9 #EDEFF1 #3DAEE9 #3DAEE9
client.focused_inactive  #A9AFB4 #A9AFB4 #EDEFF1 #A9AFB4 #A9AFB4
client.unfocused         #6B7278 #6B7278 #A9AFB4 #6B7278 #6B7278
client.urgent            #DA4453 #DA4453 #EDEFF1 #DA4453 #DA4453
