# Solarized Dark — sway client colors + wallpaper
output * bg ~/.img/wallpapers/solarized_dark_desktop.png fill

# class                  border   backgr.  text     indicator child_border
client.focused           #268BD2 #268BD2 #FDF6E3 #268BD2 #268BD2
client.focused_inactive  #657B83 #657B83 #FDF6E3 #657B83 #657B83
client.unfocused         #586E75 #586E75 #839496 #586E75 #586E75
client.urgent            #DC322F #DC322F #FDF6E3 #DC322F #DC322F
