# Vellum Light — sway client colors + wallpaper
output * bg ~/.img/wallpapers/vellum_light_desktop.png fill

# class                  border   backgr.  text     indicator child_border
client.focused           #262626 #262626 #E9E9E9 #262626 #262626
client.focused_inactive  #AEAEAE #AEAEAE #333333 #AEAEAE #AEAEAE
client.unfocused         #CCCCCC #CCCCCC #7A7A7A #CCCCCC #CCCCCC
client.urgent            #404040 #404040 #E9E9E9 #404040 #404040
