# Vellum Dark — sway client colors + wallpaper
output * bg ~/.img/wallpapers/vellum_dark_desktop.png fill

# class                  border   backgr.  text     indicator child_border
client.focused           #E6E6E6 #E6E6E6 #2E2E2E #E6E6E6 #E6E6E6
client.focused_inactive  #5E5E5E #5E5E5E #DCDCDC #5E5E5E #5E5E5E
client.unfocused         #464646 #464646 #8C8C8C #464646 #464646
client.urgent            #D2D2D2 #D2D2D2 #2E2E2E #D2D2D2 #D2D2D2
