# Litho Dark — sway client colors + wallpaper
output * bg ~/.img/wallpapers/litho_dark_desktop.png fill

# class                  border   backgr.  text     indicator child_border
client.focused           #FFFFFF #FFFFFF #000000 #FFFFFF #FFFFFF
client.focused_inactive  #595959 #595959 #FFFFFF #595959 #595959
client.unfocused         #262626 #262626 #8C8C8C #262626 #262626
client.urgent            #F2F2F2 #F2F2F2 #000000 #F2F2F2 #F2F2F2
