# Litho Light — sway client colors + wallpaper
output * bg ~/.img/wallpapers/litho_light_desktop.png fill

# class                  border   backgr.  text     indicator child_border
client.focused           #000000 #000000 #FFFFFF #000000 #000000
client.focused_inactive  #A6A6A6 #A6A6A6 #000000 #A6A6A6 #A6A6A6
client.unfocused         #D9D9D9 #D9D9D9 #737373 #D9D9D9 #D9D9D9
client.urgent            #0D0D0D #0D0D0D #FFFFFF #0D0D0D #0D0D0D
