# Nord Light — sway client colors + wallpaper
output * bg ~/.img/wallpapers/nord_light_desktop.png fill

# class                  border   backgr.  text     indicator child_border
client.focused           #5E81AC #5E81AC #ECEFF4 #5E81AC #5E81AC
client.focused_inactive  #4C566A #4C566A #ECEFF4 #4C566A #4C566A
client.unfocused         #D8DEE9 #D8DEE9 #4C566A #D8DEE9 #D8DEE9
client.urgent            #BF616A #BF616A #ECEFF4 #BF616A #BF616A
