# Harmattan Dark — sway client colors + wallpaper
output * bg ~/.img/wallpapers/harmattan_dark_desktop.png fill

# class                  border   backgr.  text     indicator child_border
client.focused           #4C5FA6 #4C5FA6 #F6EFDF #4C5FA6 #4C5FA6
client.focused_inactive  #B4A687 #B4A687 #F6EFDF #B4A687 #B4A687
client.unfocused         #473B29 #473B29 #B4A687 #473B29 #473B29
client.urgent            #C1502E #C1502E #F6EFDF #C1502E #C1502E
