# Nord Dusk — sway client colors + wallpaper
output * bg ~/.img/wallpapers/nord_dusk_desktop.png fill

# class                  border   backgr.  text     indicator child_border
client.focused           #88C0D0 #88C0D0 #3B4252 #88C0D0 #88C0D0
client.focused_inactive  #929AA9 #929AA9 #ECEFF4 #929AA9 #929AA9
client.unfocused         #434C5E #434C5E #D8DEE9 #434C5E #434C5E
client.urgent            #BF616A #BF616A #ECEFF4 #BF616A #BF616A
