# Zephyr Light — sway client colors + wallpaper
output * bg ~/.img/wallpapers/zephyr_light_desktop.png fill

# class                  border   backgr.  text     indicator child_border
client.focused           #3DAEE9 #3DAEE9 #FCFCFC #3DAEE9 #3DAEE9
client.focused_inactive  #707D8A #707D8A #FCFCFC #707D8A #707D8A
client.unfocused         #C7CBCF #C7CBCF #707D8A #C7CBCF #C7CBCF
client.urgent            #DA4453 #DA4453 #FCFCFC #DA4453 #DA4453
