# Daguerre Light — sway client colors + wallpaper
output * bg ~/.img/wallpapers/daguerre_light_desktop.png fill

# class                  border   backgr.  text     indicator child_border
client.focused           #000000 #000000 #FFFFFF #000000 #000000
client.focused_inactive  #858585 #858585 #0A0A0A #858585 #858585
client.unfocused         #B2B2B2 #B2B2B2 #737373 #B2B2B2 #B2B2B2
client.urgent            #2B2B2B #2B2B2B #FFFFFF #2B2B2B #2B2B2B
