# Zephyr Dark — sway client colors + wallpaper
output * bg ~/.img/wallpapers/zephyr_dark_desktop.png fill

# class                  border   backgr.  text     indicator child_border
client.focused           #3DAEE9 #3DAEE9 #141618 #3DAEE9 #3DAEE9
client.focused_inactive  #A1A9B1 #A1A9B1 #141618 #A1A9B1 #A1A9B1
client.unfocused         #3B4045 #3B4045 #A1A9B1 #3B4045 #3B4045
client.urgent            #DA4453 #DA4453 #FCFCFC #DA4453 #DA4453
