# Solarized Light — sway client colors + wallpaper
output * bg ~/.img/wallpapers/solarized_light_desktop.png fill

# class                  border   backgr.  text     indicator child_border
client.focused           #268BD2 #268BD2 #FDF6E3 #268BD2 #268BD2
client.focused_inactive  #839496 #839496 #FDF6E3 #839496 #839496
client.unfocused         #93A1A1 #93A1A1 #657B83 #93A1A1 #93A1A1
client.urgent            #DC322F #DC322F #FDF6E3 #DC322F #DC322F
